# Workflow to ensure whenever there is a push to Github main branch,
# Github packages and pushes the new image for the TechTrends application to DockerHub.
name: TechTrends - Package with Docker

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - "main"

jobs:
  build_and_push:
    name: Package and Push TechTrends App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: techtrends:latest
          file: ./project/techtrends/Dockerfile
