# Workflow to ensure whenever there is a push to Github main branch,
# Github packages and pushes the new image for the TechTrends application to DockerHub.
name: TechTrends - Package with Docker

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - "main"

jobs:
  build:
    name: Package and Push TechTrends App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            petetran/techtrends
          tags: |
            type=raw,value=v1.0
            type=ref,event=branch
            type=sha
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          push: true
          tags: techtrends:latest
          file: ./project/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
